
server:
  port: 0
  servlet:
    context-path: /


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://106.53.217.225:3300/example?useSSL=false
      username: root
      password: mysql_lyw
      driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    log-prefix: mybatis


